[package]
name = "tauri-plugin-dev-invoke-macros"
authors = ["Mahmoud Almontasser <almontasser@outlook.com>"]
repository = "https://github.com/almontasser/tauri-plugin-dev-invoke"
homepage = "https://github.com/almontasser/tauri-plugin-dev-invoke"
version = "0.1.1"
edition = "2021"
description = "Proc macros for tauri-plugin-dev-invoke"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
serde_json = "1"
